#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/dataware-btsync" ]; then
	update-rc.d dataware-btsync defaults >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d dataware-btsync start || exit $?
	else
		/etc/init.d/dataware-btsync start || exit $?
	fi
fi
# End automatically added section
